### ISSUE TITLE
Feat: Change tab order

### ISSUE THREAD

**Issue by andreped** [andreped/IronFlow#131]

**Comment by taheeraahmed** [comment]
Ha pluss-tegnet i midten!! resten føler jeg ikke har sååå mye å si

**Comment by andreped** [comment]
Hmm, are you sure, @taheeraahmed?

I think it matters where the other are placed based on the natural flow of the user:

<img width="419" alt="Screenshot 2024-08-11 at 16 16 07" src="https://github.com/user-attachments/assets/dd484449-6216-4d1c-82d2-8d3a21495747">

**Comment by taheeraahmed** [comment]
Det er jo standarden for veldig mange apper, men jeg ser poenget ditt
