### ISSUE TITLE
Weight/fit tracking

### ISSUE THREAD

**Issue by trilyr** [andreped/IronFlow#143]
I'd like to track my weight progress within the app to get motivated. Currently I use a pretty basic weight tracking app, it has my goal weight with a graph, I just click (+) and type in my current weight.

It would be cool to track weight to strength as well. And maybe the app could estimate muscle mass based on this, I am sure there are some relatively easy weight to relative strength correlation with muscle mass formulae that is possible to implement given. Or not, it may be highly advanced based upon the given muscle output given the specific lifting technique. 

However, the only thing I'd really like is just a basic weight to time tracking within a graphhical interface.

**Comment by andreped** [comment]
Thank you for the great suggestions, @trilyr! :]

> I'd like to track my weight progress within the app to get motivated. Currently I use a pretty basic weight tracking app, it has my goal weight with a graph, I just click (+) and type in my current weight.

That should be fairly easy to add. I can give it a go later today, if I get the time :]

> I am sure there are some relatively easy weight to relative strength correlation with muscle mass formulae that is possible to implement given.

Thats a cool idea. I have used that in other apps such as Zepp, which I use with my body weight scale at home.

**Comment by andreped** [comment]
@trilyr The latest release now supports tracking your weight over time. It also allows for plotting it to inspect progress. Nothing fancy, but the key functionality is there and ready for testing :]
